apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    app: auth-api
    service: auth-api
spec:
  ports:
    - port: 3050
      name: grpc
  selector:
    app: auth-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ripley-auth-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    app: auth-api
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      serviceAccountName: ripley-auth-api
      containers:
        - name: auth-api
          image: frperezr/banco-ripley-auth-api
          ports:
            - containerPort: 3050
          env:
            - name: AUTH_PORT
              value: "3050"
            - name: FIREBASE_API_KEY
              value: <your_key>
