apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    service: webapp
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ripley-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: ripley-webapp
      containers:
        - name: webapp
          image: frperezr/banco-ripley-webapp
          ports:
            - containerPort: 3000
