// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Token struct {
	ExpiresIn            string   `protobuf:"bytes,1,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IdToken              string   `protobuf:"bytes,3,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetExpiresIn() string {
	if m != nil {
		return m.ExpiresIn
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Data                 *Token   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetData() *Token {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SignupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupResponse struct {
	Data                 *Token   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetData() *Token {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignupResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VerifyTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenRequest) Reset()         { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()    {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{7}
}

func (m *VerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRequest.Unmarshal(m, b)
}
func (m *VerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRequest.Merge(m, src)
}
func (m *VerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRequest.Size(m)
}
func (m *VerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRequest proto.InternalMessageInfo

func (m *VerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	Data                 *Token   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenResponse) Reset()         { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()    {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{8}
}

func (m *VerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenResponse.Unmarshal(m, b)
}
func (m *VerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenResponse.Merge(m, src)
}
func (m *VerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenResponse.Size(m)
}
func (m *VerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenResponse proto.InternalMessageInfo

func (m *VerifyTokenResponse) GetData() *Token {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VerifyTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Shipping struct {
	RTienda              bool     `protobuf:"varint,1,opt,name=r_tienda,json=rTienda,proto3" json:"r_tienda,omitempty"`
	DDomicilio           bool     `protobuf:"varint,2,opt,name=d_domicilio,json=dDomicilio,proto3" json:"d_domicilio,omitempty"`
	RCercano             bool     `protobuf:"varint,3,opt,name=r_cercano,json=rCercano,proto3" json:"r_cercano,omitempty"`
	CashOnDelivery       bool     `protobuf:"varint,4,opt,name=cash_on_delivery,json=cashOnDelivery,proto3" json:"cash_on_delivery,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shipping) Reset()         { *m = Shipping{} }
func (m *Shipping) String() string { return proto.CompactTextString(m) }
func (*Shipping) ProtoMessage()    {}
func (*Shipping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{9}
}

func (m *Shipping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shipping.Unmarshal(m, b)
}
func (m *Shipping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shipping.Marshal(b, m, deterministic)
}
func (m *Shipping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shipping.Merge(m, src)
}
func (m *Shipping) XXX_Size() int {
	return xxx_messageInfo_Shipping.Size(m)
}
func (m *Shipping) XXX_DiscardUnknown() {
	xxx_messageInfo_Shipping.DiscardUnknown(m)
}

var xxx_messageInfo_Shipping proto.InternalMessageInfo

func (m *Shipping) GetRTienda() bool {
	if m != nil {
		return m.RTienda
	}
	return false
}

func (m *Shipping) GetDDomicilio() bool {
	if m != nil {
		return m.DDomicilio
	}
	return false
}

func (m *Shipping) GetRCercano() bool {
	if m != nil {
		return m.RCercano
	}
	return false
}

func (m *Shipping) GetCashOnDelivery() bool {
	if m != nil {
		return m.CashOnDelivery
	}
	return false
}

type Attribute struct {
	Displayable          bool     `protobuf:"varint,1,opt,name=displayable,proto3" json:"displayable,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Identifier           string   `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Usage                string   `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{10}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetDisplayable() bool {
	if m != nil {
		return m.Displayable
	}
	return false
}

func (m *Attribute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Attribute) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Prices struct {
	ListPrice            int64    `protobuf:"varint,1,opt,name=list_price,json=listPrice,proto3" json:"list_price,omitempty"`
	OfferPrice           int64    `protobuf:"varint,2,opt,name=offer_price,json=offerPrice,proto3" json:"offer_price,omitempty"`
	Discount             int64    `protobuf:"varint,3,opt,name=discount,proto3" json:"discount,omitempty"`
	DiscountPercentage   int64    `protobuf:"varint,4,opt,name=discount_percentage,json=discountPercentage,proto3" json:"discount_percentage,omitempty"`
	RipleyPuntos         int64    `protobuf:"varint,5,opt,name=ripley_puntos,json=ripleyPuntos,proto3" json:"ripley_puntos,omitempty"`
	FormattedListPrice   string   `protobuf:"bytes,6,opt,name=formatted_list_price,json=formattedListPrice,proto3" json:"formatted_list_price,omitempty"`
	FormattedOfferPrice  string   `protobuf:"bytes,7,opt,name=formatted_offer_price,json=formattedOfferPrice,proto3" json:"formatted_offer_price,omitempty"`
	FormattedDiscount    string   `protobuf:"bytes,8,opt,name=formatted_discount,json=formattedDiscount,proto3" json:"formatted_discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prices) Reset()         { *m = Prices{} }
func (m *Prices) String() string { return proto.CompactTextString(m) }
func (*Prices) ProtoMessage()    {}
func (*Prices) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{11}
}

func (m *Prices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prices.Unmarshal(m, b)
}
func (m *Prices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prices.Marshal(b, m, deterministic)
}
func (m *Prices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prices.Merge(m, src)
}
func (m *Prices) XXX_Size() int {
	return xxx_messageInfo_Prices.Size(m)
}
func (m *Prices) XXX_DiscardUnknown() {
	xxx_messageInfo_Prices.DiscardUnknown(m)
}

var xxx_messageInfo_Prices proto.InternalMessageInfo

func (m *Prices) GetListPrice() int64 {
	if m != nil {
		return m.ListPrice
	}
	return 0
}

func (m *Prices) GetOfferPrice() int64 {
	if m != nil {
		return m.OfferPrice
	}
	return 0
}

func (m *Prices) GetDiscount() int64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Prices) GetDiscountPercentage() int64 {
	if m != nil {
		return m.DiscountPercentage
	}
	return 0
}

func (m *Prices) GetRipleyPuntos() int64 {
	if m != nil {
		return m.RipleyPuntos
	}
	return 0
}

func (m *Prices) GetFormattedListPrice() string {
	if m != nil {
		return m.FormattedListPrice
	}
	return ""
}

func (m *Prices) GetFormattedOfferPrice() string {
	if m != nil {
		return m.FormattedOfferPrice
	}
	return ""
}

func (m *Prices) GetFormattedDiscount() string {
	if m != nil {
		return m.FormattedDiscount
	}
	return ""
}

type Product struct {
	UniqueId             string       `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	PartNumber           string       `protobuf:"bytes,2,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FullImage            string       `protobuf:"bytes,4,opt,name=full_image,json=fullImage,proto3" json:"full_image,omitempty"`
	Images               []string     `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Prices               *Prices      `protobuf:"bytes,6,opt,name=prices,proto3" json:"prices,omitempty"`
	LongDescription      string       `protobuf:"bytes,7,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Shipping             *Shipping    `protobuf:"bytes,9,opt,name=shipping,proto3" json:"shipping,omitempty"`
	ThumbnailImage       string       `protobuf:"bytes,10,opt,name=thumbnail_image,json=thumbnailImage,proto3" json:"thumbnail_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{12}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *Product) GetPartNumber() string {
	if m != nil {
		return m.PartNumber
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetFullImage() string {
	if m != nil {
		return m.FullImage
	}
	return ""
}

func (m *Product) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Product) GetPrices() *Prices {
	if m != nil {
		return m.Prices
	}
	return nil
}

func (m *Product) GetLongDescription() string {
	if m != nil {
		return m.LongDescription
	}
	return ""
}

func (m *Product) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Product) GetShipping() *Shipping {
	if m != nil {
		return m.Shipping
	}
	return nil
}

func (m *Product) GetThumbnailImage() string {
	if m != nil {
		return m.ThumbnailImage
	}
	return ""
}

type ListProductsResponse struct {
	Data                 []*Product `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProductsResponse) Reset()         { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()    {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{13}
}

func (m *ListProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResponse.Unmarshal(m, b)
}
func (m *ListProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResponse.Merge(m, src)
}
func (m *ListProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductsResponse.Size(m)
}
func (m *ListProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResponse proto.InternalMessageInfo

func (m *ListProductsResponse) GetData() []*Product {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListProductsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetProductRequest struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{14}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type GetProductResponse struct {
	Data                 *Product `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{15}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetData() *Product {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetProductResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto.RegisterType((*SignupRequest)(nil), "proto.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "proto.SignupResponse")
	proto.RegisterType((*VerifyTokenRequest)(nil), "proto.VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "proto.VerifyTokenResponse")
	proto.RegisterType((*Shipping)(nil), "proto.Shipping")
	proto.RegisterType((*Attribute)(nil), "proto.Attribute")
	proto.RegisterType((*Prices)(nil), "proto.Prices")
	proto.RegisterType((*Product)(nil), "proto.Product")
	proto.RegisterType((*ListProductsResponse)(nil), "proto.ListProductsResponse")
	proto.RegisterType((*GetProductRequest)(nil), "proto.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "proto.GetProductResponse")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 940 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xae, 0xed, 0xd8, 0xde, 0x3d, 0x76, 0xdc, 0x74, 0x92, 0x22, 0xc7, 0x55, 0x21, 0x5a, 0x54,
	0x61, 0x40, 0x94, 0xca, 0x80, 0xb8, 0xe0, 0x86, 0xa8, 0x29, 0x28, 0x52, 0x45, 0xa3, 0x4d, 0xe9,
	0x0d, 0x88, 0xd5, 0x7a, 0x67, 0x6c, 0x8f, 0xba, 0x3b, 0xb3, 0x9d, 0x99, 0x0d, 0xf8, 0x21, 0xb8,
	0xe1, 0x9e, 0xb7, 0xe1, 0x9e, 0x17, 0xe1, 0x21, 0xd0, 0x9c, 0x99, 0x5d, 0x6f, 0x48, 0x6e, 0x80,
	0xde, 0x24, 0x73, 0xbe, 0xef, 0xcc, 0x99, 0xef, 0x7c, 0xf3, 0xb3, 0x86, 0x51, 0xa9, 0xa4, 0x91,
	0x8f, 0xf1, 0x2f, 0xe9, 0xe3, 0xbf, 0xe8, 0x0b, 0xe8, 0x3f, 0x53, 0x4a, 0x2a, 0x42, 0x60, 0x2f,
	0x93, 0x94, 0x4d, 0x3b, 0x27, 0x9d, 0x79, 0x3f, 0xc6, 0x31, 0x99, 0xc2, 0xb0, 0x60, 0x5a, 0xa7,
	0x6b, 0x36, 0xed, 0x9e, 0x74, 0xe6, 0x61, 0x5c, 0x87, 0xd1, 0x10, 0xfa, 0xcf, 0x8a, 0xd2, 0x6c,
	0xa3, 0x15, 0xf4, 0x5f, 0xca, 0xd7, 0x4c, 0x90, 0x87, 0x00, 0xec, 0x97, 0x92, 0x2b, 0xa6, 0x13,
	0x2e, 0xb0, 0x4a, 0x18, 0x87, 0x1e, 0x39, 0x17, 0xe4, 0x7d, 0xd8, 0x57, 0x6c, 0xa5, 0x98, 0xde,
	0x24, 0xc6, 0xe6, 0xfb, 0x82, 0x63, 0x0f, 0xba, 0x1a, 0xc7, 0x10, 0x70, 0xea, 0xf9, 0x9e, 0x5b,
	0x90, 0x53, 0xa4, 0xa2, 0xaf, 0x61, 0xfc, 0x5c, 0xae, 0xb9, 0x88, 0xd9, 0x9b, 0x8a, 0x69, 0x43,
	0x8e, 0xa0, 0xcf, 0x8a, 0x94, 0xe7, 0x7e, 0x25, 0x17, 0x90, 0x19, 0x04, 0x65, 0xaa, 0xf5, 0xcf,
	0x52, 0x51, 0xbf, 0x40, 0x13, 0x47, 0xdf, 0xc3, 0xbe, 0xaf, 0xa0, 0x4b, 0x29, 0x34, 0x23, 0x27,
	0xb0, 0x47, 0x53, 0x93, 0x62, 0x85, 0xd1, 0x62, 0xec, 0x7c, 0x79, 0x8c, 0xcb, 0xc5, 0xc8, 0x90,
	0x08, 0xfa, 0xcc, 0x9a, 0x83, 0xb5, 0x76, 0x29, 0x68, 0x58, 0xec, 0xa8, 0xe8, 0x14, 0xf6, 0x2f,
	0xf9, 0x5a, 0x54, 0xe5, 0x7f, 0x57, 0xf6, 0x0a, 0x26, 0x75, 0x89, 0xb7, 0x2a, 0xed, 0x23, 0x20,
	0xaf, 0x98, 0xe2, 0xab, 0xad, 0x9b, 0xb8, 0xd3, 0xe7, 0x1c, 0xf6, 0xfa, 0x30, 0x88, 0x7e, 0x80,
	0xc3, 0x6b, 0xb9, 0x6f, 0x55, 0xc8, 0xaf, 0x1d, 0x08, 0x2e, 0x37, 0xbc, 0x2c, 0xb9, 0x58, 0xdb,
	0x4d, 0x56, 0x89, 0xe1, 0x4c, 0x50, 0x57, 0x36, 0x88, 0x87, 0xea, 0x25, 0x86, 0xe4, 0x3d, 0x18,
	0xd1, 0x84, 0xca, 0x82, 0x67, 0x3c, 0xe7, 0x12, 0x2b, 0x06, 0x31, 0xd0, 0xb3, 0x1a, 0x21, 0x0f,
	0x20, 0x54, 0x49, 0xc6, 0x54, 0x96, 0x0a, 0x89, 0x27, 0x24, 0x88, 0x03, 0xf5, 0xd4, 0xc5, 0x64,
	0x0e, 0x07, 0x59, 0xaa, 0x37, 0x89, 0x14, 0x09, 0x65, 0x39, 0xbf, 0x62, 0x6a, 0x3b, 0xdd, 0xc3,
	0x9c, 0x89, 0xc5, 0x5f, 0x88, 0x33, 0x8f, 0x46, 0xbf, 0x77, 0x20, 0x3c, 0x35, 0x46, 0xf1, 0x65,
	0x65, 0x6c, 0x8f, 0x23, 0xca, 0x75, 0x99, 0xa7, 0xdb, 0x74, 0x99, 0x33, 0xaf, 0xa9, 0x0d, 0x91,
	0x09, 0x74, 0x79, 0xbd, 0x6d, 0x5d, 0x4e, 0xc9, 0xbb, 0x00, 0x9c, 0x32, 0x61, 0xf8, 0x8a, 0x33,
	0xe5, 0x4f, 0x6a, 0x0b, 0xb1, 0x77, 0x49, 0xa4, 0x05, 0xc3, 0xd5, 0xc3, 0x18, 0xc7, 0xd6, 0xf6,
	0x0a, 0x6f, 0x52, 0xdf, 0xd9, 0x8e, 0x81, 0x45, 0xaf, 0xd2, 0xbc, 0x62, 0xd3, 0x81, 0x43, 0x31,
	0x88, 0xfe, 0xec, 0xc2, 0xe0, 0x42, 0xf1, 0x8c, 0x69, 0x7b, 0xad, 0x72, 0xae, 0x4d, 0x52, 0xda,
	0x10, 0xb5, 0xf5, 0xe2, 0xd0, 0x22, 0xc8, 0x5b, 0xc7, 0xe4, 0x6a, 0xc5, 0x94, 0xe7, 0xbb, 0xc8,
	0x03, 0x42, 0x2e, 0x61, 0x06, 0x01, 0xe5, 0x3a, 0x93, 0x95, 0x30, 0x28, 0xb4, 0x17, 0x37, 0x31,
	0xf9, 0x14, 0x0e, 0xeb, 0x71, 0x52, 0x32, 0x95, 0x31, 0x61, 0xac, 0xc0, 0x3d, 0x4c, 0x23, 0x35,
	0x75, 0xd1, 0x30, 0x78, 0x89, 0x79, 0x99, 0xb3, 0x6d, 0x52, 0x56, 0xc2, 0x48, 0x8d, 0xbd, 0xf4,
	0xe2, 0xb1, 0x03, 0x2f, 0x10, 0x23, 0x4f, 0xe0, 0x68, 0x25, 0x55, 0x91, 0x1a, 0xc3, 0x68, 0xd2,
	0xd2, 0xee, 0x3a, 0x24, 0x0d, 0xf7, 0xbc, 0x69, 0x62, 0x01, 0xf7, 0x77, 0x33, 0xda, 0xed, 0x0c,
	0x71, 0xca, 0x61, 0x43, 0xbe, 0xd8, 0xf5, 0xf5, 0x09, 0xec, 0x2a, 0x25, 0x4d, 0x87, 0x01, 0x4e,
	0xb8, 0xd7, 0x30, 0x67, 0x9e, 0x88, 0xfe, 0xea, 0xc2, 0xf0, 0x42, 0x49, 0x5a, 0x65, 0xc6, 0x1e,
	0xa2, 0x4a, 0xf0, 0x37, 0x15, 0x4b, 0x38, 0xf5, 0x97, 0x20, 0x70, 0xc0, 0x39, 0xb5, 0x86, 0x96,
	0xa9, 0x32, 0x89, 0xa8, 0x8a, 0x25, 0x53, 0x7e, 0xcf, 0xc1, 0x42, 0xdf, 0x21, 0xd2, 0xec, 0x6d,
	0xaf, 0xb5, 0xb7, 0x0f, 0x01, 0x56, 0x55, 0x9e, 0x27, 0xbc, 0xa8, 0xfd, 0x0b, 0xe3, 0xd0, 0x22,
	0xe7, 0x16, 0x20, 0xef, 0xc0, 0x00, 0x19, 0xeb, 0x57, 0x6f, 0x1e, 0xc6, 0x3e, 0x22, 0x8f, 0x60,
	0x80, 0x7d, 0x6a, 0xf4, 0x66, 0xb4, 0xd8, 0xf7, 0x77, 0xc7, 0x6d, 0x7d, 0xec, 0x49, 0xf2, 0x21,
	0x1c, 0xe4, 0x52, 0xac, 0x13, 0xca, 0x74, 0xa6, 0x78, 0x69, 0xb8, 0x14, 0xde, 0x99, 0xbb, 0x16,
	0x3f, 0xdb, 0xc1, 0xe4, 0x09, 0x40, 0x5a, 0x9f, 0x6b, 0x3d, 0x0d, 0x4e, 0x7a, 0xf3, 0xd1, 0xe2,
	0xc0, 0x57, 0x6d, 0x0e, 0x7c, 0xdc, 0xca, 0x21, 0x1f, 0x43, 0xa0, 0xfd, 0xcd, 0x9c, 0x86, 0xa8,
	0xe2, 0xae, 0xcf, 0xaf, 0x2f, 0x6c, 0xdc, 0x24, 0x90, 0x0f, 0xe0, 0xae, 0xd9, 0x54, 0xc5, 0x52,
	0xa4, 0xbc, 0x6e, 0x16, 0x50, 0xc8, 0xa4, 0x81, 0xb1, 0xe3, 0xe8, 0x27, 0x38, 0x72, 0xdb, 0x8b,
	0x8e, 0xeb, 0xe6, 0x39, 0x89, 0x9a, 0xe7, 0xc4, 0x2a, 0x9b, 0x34, 0xfd, 0x62, 0xda, 0xbf, 0x78,
	0x50, 0x1e, 0xc1, 0xbd, 0x6f, 0x59, 0x5d, 0xbe, 0x7e, 0xd8, 0x0e, 0xa0, 0xa7, 0x5f, 0x57, 0x7e,
	0x47, 0xed, 0x30, 0xfa, 0x11, 0x48, 0x3b, 0xed, 0x86, 0x88, 0xce, 0xff, 0x11, 0xb1, 0xf8, 0xa3,
	0x03, 0xa3, 0xd3, 0xca, 0x6c, 0x2e, 0x99, 0xba, 0xb2, 0x47, 0xf2, 0x73, 0xe8, 0xe3, 0x07, 0x86,
	0x1c, 0xfa, 0xec, 0xf6, 0x07, 0x6b, 0x76, 0x74, 0x1d, 0x74, 0x5a, 0xa2, 0x3b, 0xe4, 0x4b, 0x18,
	0xb8, 0xc7, 0x9f, 0xd4, 0x19, 0xd7, 0x3e, 0x27, 0xb3, 0xfb, 0xff, 0x40, 0x9b, 0x89, 0xdf, 0xc0,
	0xa8, 0xf5, 0x62, 0x93, 0x63, 0x9f, 0x77, 0xf3, 0xc5, 0x9f, 0xcd, 0x6e, 0xa3, 0xea, 0x3a, 0x8b,
	0xdf, 0x3a, 0x30, 0xf1, 0xcd, 0xd7, 0x9d, 0x3c, 0x05, 0xd8, 0xf9, 0x46, 0xa6, 0x7e, 0xfa, 0x0d,
	0xc7, 0x67, 0xc7, 0xb7, 0x30, 0x8d, 0xbe, 0xaf, 0x60, 0xdc, 0x3e, 0x03, 0xa4, 0xf1, 0xd0, 0xfe,
	0x6e, 0x98, 0x3d, 0xa8, 0xed, 0xb8, 0xe5, 0x98, 0x44, 0x77, 0x96, 0x03, 0x64, 0x3f, 0xfb, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x42, 0x04, 0x1e, 0xb5, 0xb3, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) Signup(ctx context.Context, req *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedAuthServiceServer) VerifyToken(ctx context.Context, req *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _AuthService_Signup_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _AuthService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	ListProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListProductsResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, "/proto.ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/proto.ProductService/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	ListProducts(context.Context, *Empty) (*ListProductsResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) GetProduct(ctx context.Context, req *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedProductServiceServer) ListProducts(ctx context.Context, req *Empty) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProducts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductService_ListProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
